apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-webhook
spec:
  selector:
    matchLabels:
      app: grafana-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana-webhook
    spec:
      containers:
      - name: grafana-webhook
        image: shaowenchen/grafana-webhook:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        env:
        - name: NOTIFICATION_XIEZUO
          value: ""
        ports:
        - containerPort: 8000